steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}/newsletter-project-course",
        "${_PATH}",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}/newsletter-project-course",
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "newsletter-project-course",
        "--image",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}/newsletter-project-course",
        "--region",
        "europe-west1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]

substitutions:
  _SERVICE_NAME: newsletter-project-course
  _PATH: .

images:
  - "europe-west1-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}/newsletter-project-course"
